name: check ifdefs

on: [push, pull_request]

jobs:
  check-ifdefs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Run check-ifdefs
        run: |
          python .github/workflows/check_ifdefs.py .github/workflows/good_defines.txt
